/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuCantante = new javax.swing.JMenu();
        menuItemCrearPersona = new javax.swing.JMenuItem();
        menuItemBuscarPersona = new javax.swing.JMenuItem();
        menuItemActualizarPersona = new javax.swing.JMenuItem();
        menuItemEliminarPersona = new javax.swing.JMenuItem();
        menuItemListarPersona = new javax.swing.JMenuItem();
        menuCompositor = new javax.swing.JMenu();
        menuItemCrearOperadora = new javax.swing.JMenuItem();
        menuItemBuscarOperadora = new javax.swing.JMenuItem();
        menuItemActualizarOperadora = new javax.swing.JMenuItem();
        menuItemEliminarOperadora = new javax.swing.JMenuItem();
        menuItemListarOperadora = new javax.swing.JMenuItem();
        menuPersona = new javax.swing.JMenu();
        menuItemCrearTelefono = new javax.swing.JMenuItem();
        menuItemBuscarTelefono = new javax.swing.JMenuItem();
        menuItemActualizarTelefono = new javax.swing.JMenuItem();
        menuItemEliminarTelefono = new javax.swing.JMenuItem();
        menuItemListarTelefono = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuItemSalirOpciones = new javax.swing.JMenuItem();

        menuCantante.setMnemonic('f');
        menuCantante.setText("Cantante");

        menuItemCrearPersona.setMnemonic('o');
        menuItemCrearPersona.setText("Crear");
        menuItemCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearPersonaActionPerformed(evt);
            }
        });
        menuCantante.add(menuItemCrearPersona);

        menuItemBuscarPersona.setMnemonic('a');
        menuItemBuscarPersona.setText("Buscar");
        menuItemBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarPersonaActionPerformed(evt);
            }
        });
        menuCantante.add(menuItemBuscarPersona);

        menuItemActualizarPersona.setMnemonic('s');
        menuItemActualizarPersona.setText("Actualizar");
        menuItemActualizarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarPersonaActionPerformed(evt);
            }
        });
        menuCantante.add(menuItemActualizarPersona);

        menuItemEliminarPersona.setMnemonic('x');
        menuItemEliminarPersona.setText("Eliminar");
        menuItemEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarPersonaActionPerformed(evt);
            }
        });
        menuCantante.add(menuItemEliminarPersona);

        menuItemListarPersona.setText("Listar");
        menuItemListarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarPersonaActionPerformed(evt);
            }
        });
        menuCantante.add(menuItemListarPersona);

        menuBar.add(menuCantante);

        menuCompositor.setMnemonic('e');
        menuCompositor.setText("Compositor");

        menuItemCrearOperadora.setMnemonic('t');
        menuItemCrearOperadora.setText("Crear");
        menuItemCrearOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearOperadoraActionPerformed(evt);
            }
        });
        menuCompositor.add(menuItemCrearOperadora);

        menuItemBuscarOperadora.setMnemonic('p');
        menuItemBuscarOperadora.setText("Buscar");
        menuItemBuscarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarOperadoraActionPerformed(evt);
            }
        });
        menuCompositor.add(menuItemBuscarOperadora);

        menuItemActualizarOperadora.setMnemonic('y');
        menuItemActualizarOperadora.setText("Actualizar");
        menuItemActualizarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarOperadoraActionPerformed(evt);
            }
        });
        menuCompositor.add(menuItemActualizarOperadora);

        menuItemEliminarOperadora.setMnemonic('d');
        menuItemEliminarOperadora.setText("Eliminar");
        menuItemEliminarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarOperadoraActionPerformed(evt);
            }
        });
        menuCompositor.add(menuItemEliminarOperadora);

        menuItemListarOperadora.setText("Listar");
        menuItemListarOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarOperadoraActionPerformed(evt);
            }
        });
        menuCompositor.add(menuItemListarOperadora);

        menuBar.add(menuCompositor);

        menuPersona.setMnemonic('h');
        menuPersona.setText("Persona");

        menuItemCrearTelefono.setMnemonic('c');
        menuItemCrearTelefono.setText("Crear");
        menuPersona.add(menuItemCrearTelefono);

        menuItemBuscarTelefono.setText("Buscar");
        menuPersona.add(menuItemBuscarTelefono);

        menuItemActualizarTelefono.setMnemonic('a');
        menuItemActualizarTelefono.setText("Actualizar");
        menuPersona.add(menuItemActualizarTelefono);

        menuItemEliminarTelefono.setText("Eliminar");
        menuPersona.add(menuItemEliminarTelefono);

        menuItemListarTelefono.setText("Listar");
        menuPersona.add(menuItemListarTelefono);

        menuBar.add(menuPersona);

        menuOpciones.setText("Opciones");

        menuItemSalirOpciones.setText("Salir");
        menuItemSalirOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirOpcionesActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemSalirOpciones);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearPersonaActionPerformed
        if (ventanaCrearPersona == null) {
            ventanaCrearPersona = new VentanaCrearPersona(personaControlador);
            desktopPane.add(ventanaCrearPersona);
        }

        ventanaCrearPersona.setVisible(true);
    }//GEN-LAST:event_menuItemCrearPersonaActionPerformed

    private void menuItemBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarPersonaActionPerformed
        if (ventanaBuscarPersona == null) {
            ventanaBuscarPersona = new VentanaBuscarPersona(personaControlador);
            desktopPane.add(ventanaBuscarPersona);
        }

        ventanaBuscarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarPersonaActionPerformed

    private void menuItemActualizarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarPersonaActionPerformed
        if (ventanaActualizarPersona == null) {
            ventanaActualizarPersona = new VentanaActualizarPersona(personaControlador);
            desktopPane.add(ventanaActualizarPersona);
        }

        ventanaActualizarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarPersonaActionPerformed

    private void menuItemEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarPersonaActionPerformed
        if (ventanaEliminarPersona == null) {
            ventanaEliminarPersona = new VentanaEliminarPersona(personaControlador);
            desktopPane.add(ventanaEliminarPersona);
        }

        ventanaEliminarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarPersonaActionPerformed

    private void menuItemListarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarPersonaActionPerformed
        if (ventanaListarPersona == null) {
            ventanaListarPersona = new VentanaListarPersona(personaControlador);
            desktopPane.add(ventanaListarPersona);
        }

        ventanaListarPersona.setVisible(true);
    }//GEN-LAST:event_menuItemListarPersonaActionPerformed

    private void menuItemCrearOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearOperadoraActionPerformed
        if (ventanaCrearOperadora == null) {
            ventanaCrearOperadora = new VentanaCrearOperadora(operadoraControlador);
            desktopPane.add(ventanaCrearOperadora);
        }

        ventanaCrearOperadora.setVisible(true);
    }//GEN-LAST:event_menuItemCrearOperadoraActionPerformed

    private void menuItemBuscarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarOperadoraActionPerformed
        if (ventanaBuscarOperadora == null) {
            ventanaBuscarOperadora = new VentanaBuscarOperadora(operadoraControlador);
            desktopPane.add(ventanaBuscarOperadora);
        }

        ventanaBuscarOperadora.setVisible(true);
    }//GEN-LAST:event_menuItemBuscarOperadoraActionPerformed

    private void menuItemActualizarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarOperadoraActionPerformed
        if (ventanaActualizarOperadora == null) {
            ventanaActualizarOperadora = new VentanaActualizarOperadora(operadoraControlador);
            desktopPane.add(ventanaActualizarOperadora);
        }

        ventanaActualizarOperadora.setVisible(true);
    }//GEN-LAST:event_menuItemActualizarOperadoraActionPerformed

    private void menuItemEliminarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarOperadoraActionPerformed
        if (ventanaEliminarOperadora == null) {
            ventanaEliminarOperadora = new VentanaEliminarOperadora(operadoraControlador);
            desktopPane.add(ventanaEliminarOperadora);
        }

        ventanaEliminarOperadora.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarOperadoraActionPerformed

    private void menuItemListarOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarOperadoraActionPerformed
        if (ventanaListarOperadora == null) {
            ventanaListarOperadora = new VentanaListarOperadora(operadoraControlador);
            desktopPane.add(ventanaListarOperadora);
        }

        ventanaListarOperadora.setVisible(true);
    }//GEN-LAST:event_menuItemListarOperadoraActionPerformed

    private void menuItemSalirOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirOpcionesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirOpcionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCantante;
    private javax.swing.JMenu menuCompositor;
    private javax.swing.JMenuItem menuItemActualizarOperadora;
    private javax.swing.JMenuItem menuItemActualizarPersona;
    private javax.swing.JMenuItem menuItemActualizarTelefono;
    private javax.swing.JMenuItem menuItemBuscarOperadora;
    private javax.swing.JMenuItem menuItemBuscarPersona;
    private javax.swing.JMenuItem menuItemBuscarTelefono;
    private javax.swing.JMenuItem menuItemCrearOperadora;
    private javax.swing.JMenuItem menuItemCrearPersona;
    private javax.swing.JMenuItem menuItemCrearTelefono;
    private javax.swing.JMenuItem menuItemEliminarOperadora;
    private javax.swing.JMenuItem menuItemEliminarPersona;
    private javax.swing.JMenuItem menuItemEliminarTelefono;
    private javax.swing.JMenuItem menuItemListarOperadora;
    private javax.swing.JMenuItem menuItemListarPersona;
    private javax.swing.JMenuItem menuItemListarTelefono;
    private javax.swing.JMenuItem menuItemSalirOpciones;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuPersona;
    // End of variables declaration//GEN-END:variables
}
